### ISSUE TITLE
unable to download. Name 'p' is not defined

### ISSUE THREAD

**Issue by joel5638** [theAIGuysCode/Download-Google-Images#2]
Im trying to download person and car images. while running the python script. i get this error.

File "download_images.py", line 40, in <module>

    print("[INFO] error downloading {}...skipping".format(p))

NameError: name 'p' is not defined

and the urls.txt is empty. it has just "undefined"

**Comment by Keshavkant** [comment]
I am facing the same problem, Any leads @joel5638 ? 
Thank You!

**Comment by FriedrichHayec** [comment]
I am facing the same problem too, Any leads @joel5638?

**Comment by FriedrichHayec** [comment]
Thank you!

**Comment by Rasantis** [comment]
Same problem , someone could help ?
